on: 
  push:
    branches:
      - main
      - master
      - compositionAPI
      
  pull_request:
    branches:
      -main
      -
jobs:
  test:
    name: components unit tests on node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8','12','16']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Nodejs ${{ matrix.node_version}}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node_version }}
        
    - name: npm install, build and test
      run: |
        npm install
        npm run test
        
